export { default as pdfIcon } from "../assets/pdf-icon.svg";
export { default as docs } from "../assets/docs_icon.png";
export { default as eyeIcon } from "../assets/eye.svg";
export { default as downloadIcon } from "../assets/download.svg";
export { default as icon1 } from "../assets/jobs icon/1.svg";
export { default as icon2 } from "../assets/jobs icon/2.svg";
export { default as icon3 } from "../assets/jobs icon/3.svg";
export { default as icon4 } from "../assets/jobs icon/4.svg";
export { default as icon5 } from "../assets/jobs icon/5.svg";
export { default as icon6 } from "../assets/jobs icon/6.svg";
export { default as icon7 } from "../assets/jobs icon/7.svg";
export { default as icon8 } from "../assets/jobs icon/8.svg";
export { default as crossIcon } from "../assets/jobs icon/x.svg";
export { default as check } from "../assets/jobs icon/check.svg";
export { default as yellow } from "../assets/postjob/yellow.svg";
export { default as pink } from "../assets/postjob/pink.svg";
export { default as blue } from "../assets/postjob/blue.svg";
export { default as green } from "../assets/postjob/green.svg";
export { default as docIcon } from "../assets/postjob/docs.svg";
export { default as msgIcon } from "../assets/postjob/msg.svg";
export { default as chevronDown } from "../assets/chevronDown.svg";
